# Generated by `generate_components.py`, then modified.

from __future__ import annotations

from typing import ClassVar

import pandas
from pydantic import BaseModel, Field

from typsa.literal_types import ControlType
from typsa.time_variation import IntegerSnapshots, Series, Static, TimestampSnapshots

from ._base_component import (
    BaseComponent,
    BaseDynamicResults,
    BaseStaticResults,
)


class Coordinates(BaseModel):
    x: float = 0.0
    """Longitude."""

    y: float = 0.0
    """Latitude."""


class Bus[T: Static | TimestampSnapshots | IntegerSnapshots = Static](BaseComponent[T]):
    """Fundamental node where all components attach.

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/buses/)
    """

    class_name: ClassVar = "Bus"

    name: str = Field(min_length=1)
    """Unique name."""

    v_nom: float | None = None
    """Nominal voltage."""

    coordinates: Coordinates | None = None
    """Coordinates. The Spatial Reference System Identifier (SRID) can be set in `n.srid`."""

    carrier: str = Field(default="AC", min_length=1)
    """Carrier, such as "AC", "DC", "heat" or "gas"."""

    unit: str = "MW"
    """Unit of the bus' carrier if the implicitly assumed unit ("MW") is inappropriate (e.g. "t/h"). Only descriptive. Does not influence any PyPSA functions."""

    location: str | None = None
    """Location of the bus. Does not influence the optimisation model but can be used for aggregation with `n.statistics`."""

    v_mag_pu_set: float | Series[T] = 1.0
    """Voltage magnitude set point, per unit of `v_nom`."""


class BusOptimizationStaticResults(BaseStaticResults):
    control: ControlType = "PQ"
    """P,Q,V control strategy for power flow, must be "PQ", "PV" or "Slack". Note that this attribute is an output inherited from the controls of the generators attached to the bus."""

    generator: str
    """Name of slack generator attached to slack bus."""

    sub_network: str
    """Name of connected sub-network to which bus belongs. This attribute is set by `n.determine_network_topology()`."""


class _BusDynamicResults(BaseDynamicResults):
    p: pandas.DataFrame
    """Active power at bus (positive if net generation at bus)."""


class BusOptimizationDynamicResults(_BusDynamicResults):
    marginal_price: pandas.DataFrame
    """Shadow price from energy balance constraint."""


class BusPfDynamicResults(_BusDynamicResults):
    v_mag_pu: pandas.DataFrame
    """Voltage magnitude, per unit of `v_nom`."""

    v_ang: pandas.DataFrame
    """Voltage angle."""


class BusNonlinearPfDynamicResults(BusPfDynamicResults):
    q: pandas.DataFrame
    """Reactive power (positive if net generation at bus)."""
