# Generated by `generate_components.py`, then modified.

from __future__ import annotations

from typing import Literal

from pydantic import Field

from ._base_component import BaseComponent


class Carrier(BaseComponent):
    """Energy carriers of buses (e.g. "AC" for alternating current, "DC" for direct current, "hydrogen", or "heat") or technologies of other components (e.g. "wind", "gas turbine", "electrolyser", or "heat pump").

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/carriers/)
    """

    class_name: Literal["Carrier"] = "Carrier"  # type: ignore

    name: str = Field(min_length=1)
    """Unique name."""

    co2_emissions: float = Field(default=0.0, ge=0.0)
    """Emissions in tCO₂ per MWh of primary energy (e.g. methane has 0.2 tCO₂/MWh_thermal)."""

    color: str | None = Field(default=None, min_length=1)
    """Color for plotting (e.g. `matplotlib` [named colors](https://matplotlib.org/stable/gallery/color/named_colors.html) or hexadecimal color codes like "#AB9812")."""

    nice_name: str | None = Field(default=None, min_length=1)
    """Descriptive name for statistics and visualisations (e.g. "Natural Gas" for carrier `gas`)."""

    max_growth: float | None = Field(default=None, ge=0.0)
    """Maximum new installed capacity per investment period."""

    max_relative_growth: float = Field(default=0.0, ge=0.0)
    """Maximum capacity ratio for new installed capacity per investment period."""
