# Generated by `generate_components.py`.

from __future__ import annotations

from typing import Literal

from ._base_component import BaseComponent


class Carrier(BaseComponent):
    """Energy carriers of buses (e.g. "AC" for alternating current, "DC" for direct current, "hydrogen", or "heat") or technologies of other components (e.g. "wind", "gas turbine", "electrolyser", or "heat pump").

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/carriers/)
    """

    class_name: Literal["Carrier"] = "Carrier"  # type: ignore

    name: str
    """Unique name."""

    co2_emissions: float
    """Emissions in tCO~2~ per MWh of primary energy (e.g. methane has 0.2 tCO~2~/MWh~thermal~)."""

    color: str | None = None
    """Color for plotting (e.g. `matplotlib` [named colors](https://matplotlib.org/stable/gallery/color/named_colors.html) or hexadecimal color codes like "#AB9812")."""

    nice_name: str | None = None
    """Descriptive name for statistics and visualisations (e.g. "Natural Gas" for carrier `gas`)."""

    max_growth: float | None = None
    """Maximum new installed capacity per investment period."""

    max_relative_growth: float
    """Maximum capacity ratio for new installed capacity per investment period."""
