# Generated by `generate_components.py`.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import pandas

from ._base_component import (
    BaseComponent,
    BaseDynamicResults,
    BaseResults,
    BaseStaticResults,
)


class Generator(BaseComponent):
    """Power generator for the bus carrier it attaches to.

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/generators/)
    """

    class_name: Literal["Generator"] = "Generator"  # type: ignore

    name: str
    """Unique name."""

    bus: str
    """Name of bus to which generator is attached."""

    control: str
    """P,Q,V control strategy for power flow, must be "PQ", "PV" or "Slack". Only relevant for "AC" and "DC" buses."""

    p_nom: float
    """Nominal power for limits  on `p` in optimization. Ignored if `p_nom_extendable=True`."""

    p_nom_mod: float
    """Nominal power of the generator module (e.g. fixed unit size of a nuclear power plant). Introduces integer variables if set."""

    p_nom_extendable: bool
    """Switch to allow capacity `p_nom` to be extended in optimization."""

    p_nom_min: float
    """If `p_nom` is extendable in optimization, set its minimum value."""

    p_nom_max: float | None = None
    """If `p_nom` is extendable in optimization, set its maximum value (e.g. limited by technical potential)."""

    p_nom_set: float | None = None
    """If `p_nom` is extendable in optimization, set its value."""

    p_min_pu: float
    """The minimum output for each snapshot per unit of `p_nom` for the optimization (e.g. a minimal dispatch level for conventional power plants). Note that if `committable=False` and `p_min_pu>0`, this represents a must-run condition."""

    p_max_pu: float
    """The maximum output for each snapshot per unit of `p_nom` for the optimization (e.g. changing availability of renewable generators due to weather conditions or a de-rating of conventional power plants)."""

    p_set: float | None = None
    """Active power set point (for optimisation and power flow)."""

    e_sum_min: float | None = None
    """The minimum total energy produced during a single optimization horizon."""

    e_sum_max: float | None = None
    """The maximum total energy produced during a single optimization horizon."""

    q_set: float
    """Reactive power set point (for power flow)."""

    sign: float
    """Sign denoting the orientation of the dispatch variable (e.g. positive for generation, negative for consumption)."""

    carrier: str | None = None
    """Prime mover energy carrier (e.g. coal, gas, wind, solar); required for global constraints on primary energy in optimisation."""

    marginal_cost: float
    """Marginal cost of production of 1 MWh."""

    marginal_cost_quadratic: float
    """Quadratic marginal cost of production of 1 MWh."""

    active: bool
    """Whether to consider the component in optimization or not."""

    build_year: int
    """Build year of the generator."""

    lifetime: float | None = None
    """Lifetime of the generator."""

    capital_cost: float
    """Fixed period costs of extending `p_nom` by 1 MW, including periodized investment costs and periodic fixed O&M costs (e.g. annuitized investment costs)."""

    efficiency: float
    """Ratio output and primary energy carrier input (e.g. 0.4 MWh~elec~/MWh~fuel~). This is required for global constraints on primary energy in optimization."""

    committable: bool
    """Apply unit commitment constraints. This is only possible with `p_nom_extendable=False`."""

    start_up_cost: float
    """Cost to start up the generator. Only used if `committable=True`."""

    shut_down_cost: float
    """Cost to shut down the generator. Only used if `committable=True`."""

    stand_by_cost: float
    """Stand-by cost for running the generator. This cost is incurred whenever the status is 1 (including when the dispatch decision is zero)."""

    min_up_time: int
    """Minimum number of snapshots for status to be 1. Only used if `committable=True`. Does not consider snapshot weightings."""

    min_down_time: int
    """Minimum number of snapshots for status to be 0. Only used if `committable=True`. Does not consider snapshot weightings."""

    up_time_before: int
    """Number of snapshots that the generator was online before `n.snapshots` start. Only used if `committable=True` and `min_up_time>0`. Does not consider snapshot weightings."""

    down_time_before: int
    """Number of snapshots that the generator was offline before `n.snapshots` start. Only used if `committable=True` and `min_down_time>0`. Does not consider snapshot weightings."""

    ramp_limit_up: float | None = None
    """Maximum active power increase from one snapshot to the next, per unit of the nominal power. Ignored if NaN. Does not consider snapshot weightings."""

    ramp_limit_down: float | None = None
    """Maximum active power decrease from one snapshot to the next, per unit of the nominal power. Ignored if NaN. Does not consider snapshot weightings."""

    ramp_limit_start_up: float
    """Maximum active power increase at start up, per unit of the nominal power. Only used if `committable=True`."""

    ramp_limit_shut_down: float
    """Maximum active power decrease at shut down, per unit of the nominal power. Only used if `committable=True`."""

    weight: float
    """Weighting of a generator. Only used for network clustering."""


class GeneratorStaticResults(BaseStaticResults):
    p_nom_opt: float
    """Optimised nominal capacity."""


class GeneratorDynamicResults(BaseDynamicResults):
    p: pandas.DataFrame
    """Active power at bus (positive if net generation)."""

    q: pandas.DataFrame
    """Reactive power (positive if net generation)."""

    status: pandas.DataFrame
    """Status in the snapshot (1 is on, 0 is off). Only returned if `committable=True`."""

    start_up: pandas.DataFrame
    """Whether the unit was started in the snapshot (1 is yes, 0 is no). Only returned if `committable=True`."""

    shut_down: pandas.DataFrame
    """Whether the unit was shut down in the snapshot (1 is yes, 0 is no).  Only returned if `committable=True`."""

    mu_upper: pandas.DataFrame
    """Shadow price of upper `p_nom` limit."""

    mu_lower: pandas.DataFrame
    """Shadow price of lower `p_nom` limit."""

    mu_p_set: pandas.DataFrame
    """Shadow price of fixed power generation `p_set`."""

    mu_ramp_limit_up: pandas.DataFrame
    """Shadow price of upper ramp up limit."""

    mu_ramp_limit_down: pandas.DataFrame
    """Shadow price of lower ramp down limit."""


@dataclass(repr=False)
class GeneratorResults(BaseResults):
    static: dict[str, GeneratorStaticResults]
    dynamic: GeneratorDynamicResults
