# Generated by `generate_components.py`.

from __future__ import annotations

from typing import Literal

from ._base_component import BaseComponent, BaseStaticResults


class GlobalConstraint(BaseComponent):
    """Constraints in the optimisation problem that apply to multiple components at once.

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/global_constraints/)
    """

    class_name: Literal["GlobalConstraint"] = "GlobalConstraint"  # type: ignore

    name: str
    """Unique name."""

    type: str
    """Type of constraint (e.g. "primary energy", "tech_capacity_expansion_limit", "operational_limit", "transmission_volume_expansion_limit", "transmission_expansion_cost_limit")."""

    investment_period: float | None = None
    """Investment period for which the constraint is applied. If not specified, the constraint is applied to all investment periods together."""

    bus: str | None = None
    """Bus to which the global constraint applies. Only relevant for `type="tech_expansion_limit". If not specified, the constraint applies to all buses."""

    carrier_attribute: str
    """If the global constraint is connected with a carrier, name the associated carrier attribute. This must appear as a column in `n.carriers`."""

    sense: str
    """Constraint sense; must be one of <=, == or >=."""

    constant: float
    """Constant for right-hand-side of constraint for optimisation period. For a CO~2~ constraint, this would be tonnes of CO~2~."""


class GlobalConstraintStaticResults(BaseStaticResults):
    mu: float
    """Shadow price of global constraint."""
