# Generated by `generate_components.py`.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import pandas

from ._base_component import (
    BaseComponent,
    BaseDynamicResults,
    BaseResults,
    BaseStaticResults,
)


class Line(BaseComponent):
    """Lines include distribution and transmission lines, overhead lines and cables.

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/lines/)
    """

    class_name: Literal["Line"] = "Line"  # type: ignore

    name: str
    """Unique name."""

    bus0: str
    """Name of origin bus to which branch is attached."""

    bus1: str
    """Name of destination bus to which branch is attached."""

    type: str | None = None
    """Name of line standard type. If this is not an empty string "", the line standard type impedance parameters are multiplied with the `length` and divided/multiplied by `num_parallel` to compute `x`, `r`, etc. This will override any values set in `r`, `x, and `b`. If the string is empty, values manually provided for `r`, `x`, etc. are taken."""

    x: float
    """Series reactance, must be non-zero for AC branch for linearised power flow equations. If the line has series inductance $L$ in Henries then $x = 2\\pi f L$ where $f$ is the frequency in Hertz. Series impedance $z = r + jx$ must be non-zero for non-linear power flow calculations. Ignored if `type` defined."""

    r: float
    """Series resistance, must be non-zero for DC branch for linearised power flow equations. Series impedance $z = r + jx$ must be non-zero for the non-linear power flow. Ignored if `type` defined."""

    g: float
    """Shunt conductivity. Shunt admittance is $y = g + jb$."""

    b: float
    """Shunt susceptance. If the line has shunt capacitance $C$ in Farads then $b = 2\\pi f C$ where $f$ is the frequency in Hertz. Shunt admittance is $y = g + jb$. Ignored if `type` defined."""

    s_nom: float
    """Limit of apparent power which can pass through branch in either direction. Ignored if `s_nom_extendable=True`."""

    s_nom_mod: float
    """Modular unit size of line expansion of `s_nom` (e.g. fixed rating of added circuit). Introduces integer variables."""

    s_nom_extendable: bool
    """Switch to allow capacity `s_nom` to be extended in optimisation."""

    s_nom_min: float
    """If `s_nom_extendable=True`, set the minimum value of `s_nom_opt`."""

    s_nom_max: float | None = None
    """If `s_nom_extendable=True`, set the maximum value of `s_nom_opt`."""

    s_nom_set: float | None = None
    """If `s_nom` is extendable in optimization, set the value of `s_nom_opt`."""

    s_max_pu: float
    """The maximum allowed absolute apparent power flow per unit of `s_nom` for the optimisation (e.g. can set `s_max_pu<1` to approximate $N-1$ contingency factor, or can be time-varying to represent weather-dependent dynamic line rating for overhead lines)."""

    capital_cost: float
    """Fixed period costs of extending `s_nom` by 1 MVA, including periodized investment costs and periodic fixed O&M costs (e.g. annuitized investment costs). Any `length` factor must already be included here."""

    active: bool
    """Whether to consider the component in optimisation or not."""

    build_year: int
    """Build year of line."""

    lifetime: float | None = None
    """Lifetime of line."""

    length: float
    """Length of line used when `type` is set. Also useful for calculating `capital_cost`."""

    carrier: str
    """Type of current. "AC" is the only valid value for lines."""

    terrain_factor: float
    """Terrain factor for increasing `length` for `capital_cost` calculation."""

    num_parallel: float
    """When `type` is set, this is the number of parallel circuits. Can also be fractional. If `type` is empty "" this value is ignored."""


class LineStaticResults(BaseStaticResults):
    sub_network: str
    """Name of sub-network to which lines belongs, as calculated by `n.determine_network_topology()`. Do not set by hand."""

    x_pu: float
    """Per unit series reactance calculated by `n.calculate_dependent_values()` from `x` and `n.buses.v_nom`."""

    r_pu: float
    """Per unit series resistance calculated by `n.calculate_dependent_values()` from `r` and `n.buses.v_nom`."""

    g_pu: float
    """Per unit shunt conductivity calculated by `n.calculate_dependent_values()` from `g` and `n.buses.v_nom`."""

    b_pu: float
    """Per unit shunt susceptance calculated by `n.calculate_dependent_values()` from `b` and `n.buses.v_nom`."""

    x_pu_eff: float
    """Effective per unit series reactance for linear power flow, calculated by `n.calculate_dependent_values()` from `x` and `n.buses.v_nom`."""

    r_pu_eff: float
    """Effective per unit series resistance for linear power flow, calculated by `n.calculate_dependent_values()` from `r` and `n.buses.v_nom`."""

    s_nom_opt: float
    """Optimised nominal capacity for apparent power."""


class LineDynamicResults(BaseDynamicResults):
    p0: pandas.DataFrame
    """Active power at `bus0` (positive if branch is withdrawing power from `bus0`)."""

    q0: pandas.DataFrame
    """Reactive power at `bus0` (positive if branch is withdrawing power from `bus0`)."""

    p1: pandas.DataFrame
    """Active power at `bus1` (positive if branch is withdrawing power from `bus1`)."""

    q1: pandas.DataFrame
    """Reactive power at `bus1` (positive if branch is withdrawing power from `bus1`)."""

    mu_lower: pandas.DataFrame
    """Shadow price of lower `s_nom` limit $-F \\leq f$. Always non-negative."""

    mu_upper: pandas.DataFrame
    """Shadow price of upper `s_nom` limit $f \\leq F$. Always non-negative."""


@dataclass(repr=False)
class LineResults(BaseResults):
    static: dict[str, LineStaticResults]
    dynamic: LineDynamicResults
