# Generated by `generate_components.py`.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import pandas

from ._base_component import (
    BaseComponent,
    BaseDynamicResults,
    BaseResults,
    BaseStaticResults,
)


class Link(BaseComponent):
    """Links are used for controllable directed flows between two or more buses with arbitrary energy carriers (e.g. HVDC links, converters, conversions between carriers).

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/links/)
    """

    class_name: Literal["Link"] = "Link"  # type: ignore

    name: str
    """Unique name."""

    bus0: str
    """Name of origin bus to which link is attached."""

    bus1: str
    """Name of first destination bus to which link is attached. Further destination buses (`bus2`, `bus3`, etc.) are automatically expanded as needed."""

    carrier: str
    """Carrier of the link describing its technology (e.g. gas boiler, electrolyser, HVDC link)."""

    efficiency: float
    """Efficiency of energy transfer from `bus0` to `bus1`. Can be time-dependent (e.g. to represent temperature-dependent heat pump COP).  Further efficiency attributes for further buses (e.g. `bus2`, `bus3`, etc.) are automatically expanded as needed (e.g. `efficiency2`, `efficiency3`, etc.)."""

    active: bool
    """Whether to consider the component in basic functionality or not."""

    build_year: int
    """Build year."""

    lifetime: float | None = None
    """Lifetime."""

    p_nom: float
    """Limit of power which can pass through link (in units of `bus0`). Ignored if `p_nom_extendable=True`."""

    p_nom_mod: float
    """Unit size of link module (e.g. fixed blocks of 100 MW)."""

    p_nom_extendable: bool
    """Switch to allow capacity `p_nom` to be extended."""

    p_nom_min: float
    """If `p_nom_extendable=True`, set its minimum value."""

    p_nom_max: float | None = None
    """If `p_nom_extendable=True`, set its maximum value."""

    p_nom_set: float | None = None
    """If `p_nom` is extendable in optimization, set its value."""

    p_set: float | None = None
    """The dispatch set point for `p0` of the link (for optimisation and power flow)."""

    p_min_pu: float
    """Minimal dispatch per unit of `p_nom` for the link. Can also be negative."""

    p_max_pu: float
    """Maximal dispatch per unit of `p_nom` for the link. Can also be negative."""

    capital_cost: float
    """Fixed period costs of extending `p_nom` by 1 MW (unit of `bus0`), including periodized investment costs and periodic fixed O&M costs (e.g. annuitized investment costs). Any `length` factor must already be included here."""

    marginal_cost: float
    """Marginal cost of 1 MWh consumption from `bus0` (e.g. including variable operation and maintenance costs of an electrolyser but excluding electricity costs)."""

    marginal_cost_quadratic: float
    """Quadratic marginal cost for 1 MWh of consumption from `bus0`."""

    stand_by_cost: float
    """Stand-by cost for operating the link. This cost is incurred whenever the status is 1 (including when dispatch decision is zero)."""

    length: float
    """Length of the link. Useful for calculating `capital_cost` for HVDC connections."""

    terrain_factor: float
    """Terrain factor for increasing `capital_cost` calculated from `length`."""

    committable: bool
    """Apply unit commitment constraints. This is only possible with `p_nom_extendable=False`."""

    start_up_cost: float
    """Cost to start up the link. Only used if `committable=True`."""

    shut_down_cost: float
    """Cost to shut down the link. Only used if `committable=True`."""

    min_up_time: int
    """Minimum number of snapshots for status to be 1.  Only used if `committable=True`. Does not consider snapshot weightings."""

    min_down_time: int
    """Minimum number of snapshots for status to be 0.  Only used if `committable=True`. Does not consider snapshot weightings."""

    up_time_before: int
    """Number of snapshots that the link was online before network.snapshots start. Only read if `committable=True` and `min_up_time>0`. Does not consider snapshot weightings."""

    down_time_before: int
    """Number of snapshots that the link was offline before network.snapshots start. Only read if `committable=True` and `min_down_time>0`. Does not consider snapshot weightings."""

    ramp_limit_up: float | None = None
    """Maximum increase from one snapshot to the next, per unit of `p_nom`. Ignored if NaN. Does not consider snapshot weightings."""

    ramp_limit_down: float | None = None
    """Maximum decrease from one snapshot to the next, per unit of `p_nom`. Ignored if NaN. Does not consider snapshot weightings."""

    ramp_limit_start_up: float
    """Maximum increase at start up, per unit of `p_nom`. Only used if `committable=True`."""

    ramp_limit_shut_down: float
    """Maximum decrease at shut down, per unit of `p_nom`. Only used if `committable=True`."""


class LinkStaticResults(BaseStaticResults):
    p_nom_opt: float
    """Optimised nominal capacity."""


class LinkDynamicResults(BaseDynamicResults):
    p0: pandas.DataFrame
    """Power at `bus0` (positive if link is withdrawing from `bus0`)."""

    p1: pandas.DataFrame
    """Power at `bus1` (positive if link is withdrawing from `bus1`)."""

    status: pandas.DataFrame
    """Status in the snapshot (1 is on, 0 is off). Only returned if `committable=True`."""

    start_up: pandas.DataFrame
    """Whether the unit was started in the snapshot (1 is yes, 0 is no). Only returned if `committable=True`."""

    shut_down: pandas.DataFrame
    """Whether the unit was shut down in the snapshot (1 is yes, 0 is no).  Only returned if `committable=True`."""

    mu_lower: pandas.DataFrame
    """Shadow price of lower `p_nom` limit  $-F \\leq f$. Always non-negative."""

    mu_upper: pandas.DataFrame
    """Shadow price of upper `p_nom` limit $f \\leq F$. Always non-negative."""

    mu_p_set: pandas.DataFrame
    """Shadow price of fixed dispatch `p_set`."""

    mu_ramp_limit_up: pandas.DataFrame
    """Shadow price of upper ramp up limit."""

    mu_ramp_limit_down: pandas.DataFrame
    """Shadow price of lower ramp down limit."""


@dataclass(repr=False)
class LinkResults(BaseResults):
    static: dict[str, LinkStaticResults]
    dynamic: LinkDynamicResults
