# Generated by `generate_components.py`, then modified.

from __future__ import annotations

from typing import ClassVar

import pandas
from pydantic import Field

from typsa.literal_types import SignType
from typsa.time_variation import IntegerSnapshots, Series, Static, TimestampSnapshots

from ._base_component import BaseComponent, BaseDynamicResults


class Load[T: Static | TimestampSnapshots | IntegerSnapshots = Static](
    BaseComponent[T]
):
    """Loads represent a demand at the bus they are connected to (e.g. PQ power consumer).

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/loads/)
    """

    class_name: ClassVar = "Load"

    bus: str = Field(min_length=1)
    """Name of bus to which load is attached."""

    carrier: str | None = Field(default=None, min_length=1)
    """Carrier of the load."""

    p_set: float | Series[T] = 0.0
    """Active power consumption (positive if the load is consuming power)."""

    q_set: float | Series[T] = 0.0
    """Reactive power consumption (positive if the load is inductive)."""

    sign: SignType = -1
    """Sign (opposite sign to generator)."""

    active: bool = True
    """Whether to consider the component in optimisation or not."""


class LoadBaseDynamicResults(BaseDynamicResults):
    p: pandas.DataFrame
    """Active power at bus (positive if net load)."""


class LoadOptimizationDynamicResults(LoadBaseDynamicResults):
    pass


class LoadPfDynamicResults(LoadBaseDynamicResults):
    pass


class LoadNonlinearPfDynamicResults(LoadPfDynamicResults):
    q: pandas.DataFrame
    """Reactive power (positive if net load)."""
