# Generated by `generate_components.py`.

from __future__ import annotations

from typing import Literal

import pandas

from ._base_component import BaseComponent, BaseDynamicResults


class Load(BaseComponent):
    """Loads represent a demand at the bus they are connected to (e.g. PQ power consumer).

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/loads/)
    """

    class_name: Literal["Load"] = "Load"  # type: ignore

    name: str
    """Unique name."""

    bus: str
    """Name of bus to which load is attached."""

    carrier: str | None = None
    """Carrier of the load."""

    p_set: float
    """Active power consumption (positive if the load is consuming power)."""

    q_set: float
    """Reactive power consumption (positive if the load is inductive)."""

    sign: float
    """Sign (opposite sign to generator)."""

    active: bool
    """Whether to consider the component in optimisation or not."""


class LoadDynamicResults(BaseDynamicResults):
    p: pandas.DataFrame
    """Active power at bus (positive if net load)."""

    q: pandas.DataFrame
    """Reactive power (positive if net load)."""
