# Generated by `generate_components.py`, then modified.

from __future__ import annotations

from typing import Literal

import pandas
from pydantic import Field

from typsa.literal_types import SignType

from ._base_component import (
    BaseComponent,
    BaseDynamicResults,
    BaseStaticResults,
)


class ShuntImpedance(BaseComponent):
    """Shunt with voltage-dependent admittance.

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/shunt_impedances/)
    """

    class_name: Literal["ShuntImpedance"] = "ShuntImpedance"  # type: ignore

    name: str = Field(min_length=1)
    """Unique name."""

    bus: str = Field(min_length=1)
    """Name of bus to which shunt impedance is attached."""

    g: float = Field(default=0.0, ge=0.0)
    """Shunt conductivity."""

    b: float = Field(default=0.0, ge=0.0)
    """Shunt susceptance."""

    sign: SignType = -1
    """Power sign (sign convention so that `g>0` withdraws `p` from bus)."""

    active: bool = True
    """Whether to consider the component as active component or not."""


class ShuntImpedanceStaticResults(BaseStaticResults):
    g_pu: float = 0.0
    """Calculated from `g` and `n.buses.v_nom`."""

    b_pu: float = 0.0
    """Calculated from `b` and `n.buses.v_nom`."""


class ShuntImpedanceDynamicResults(BaseDynamicResults):
    p: pandas.DataFrame
    """Active power at bus (positive if net load)."""

    q: pandas.DataFrame
    """Reactive power (positive if net generation)."""
