# Generated by `generate_components.py`.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import pandas

from ._base_component import (
    BaseComponent,
    BaseDynamicResults,
    BaseResults,
    BaseStaticResults,
)


class ShuntImpedance(BaseComponent):
    """Shunt with voltage-dependent admittance.

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/shunt_impedances/)
    """

    class_name: Literal["ShuntImpedance"] = "ShuntImpedance"  # type: ignore

    name: str
    """Unique name."""

    bus: str
    """Name of bus to which shunt impedance is attached."""

    g: float
    """Shunt conductivity."""

    b: float
    """Shunt susceptance."""

    sign: float
    """Power sign (sign convention so that `g>0` withdraws `p` from bus)."""

    active: bool
    """Whether to consider the component as active component or not."""


class ShuntImpedanceStaticResults(BaseStaticResults):
    g_pu: float
    """Calculated from `g` and `n.buses.v_nom`."""

    b_pu: float
    """Calculated from `b` and `n.buses.v_nom`."""


class ShuntImpedanceDynamicResults(BaseDynamicResults):
    p: pandas.DataFrame
    """Active power at bus (positive if net load)."""

    q: pandas.DataFrame
    """Reactive power (positive if net generation)."""


@dataclass(repr=False)
class ShuntImpedanceResults(BaseResults):
    static: dict[str, ShuntImpedanceStaticResults]
    dynamic: ShuntImpedanceDynamicResults
