# Generated by `generate_components.py`.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import pandas

from ._base_component import (
    BaseComponent,
    BaseDynamicResults,
    BaseResults,
    BaseStaticResults,
)


class Store(BaseComponent):
    """Stores provide fundamental inter-temporal storage functionality not limited in charging or discharging power.

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/stores/)
    """

    class_name: Literal["Store"] = "Store"  # type: ignore

    name: str
    """Unique name."""

    bus: str
    """Name of bus to which store is attached."""

    carrier: str
    """Carrier of the store."""

    e_nom: float
    """Nominal energy capacity (i.e. limit on `e`). Ignored if `e_nom_extendable=True`."""

    e_nom_mod: float
    """Nominal energy capacity of the store module. Introduces integer variables if set."""

    e_nom_extendable: bool
    """Switch to allow capacity `e_nom` to be extended in optimisation."""

    e_nom_min: float
    """If `e_nom_extendable=True`, set the minimum value of `e_nom_opt`."""

    e_nom_max: float | None = None
    """If `e_nom_extendable=True`, set the maximum value of `e_nom_opt`."""

    e_nom_set: float | None = None
    """If `e_nom_extendable=True`, set the value of `e_nom_opt`."""

    e_min_pu: float
    """Minimal value of `e` relative to `e_nom` for the optimisation."""

    e_max_pu: float
    """Maximal value of `e` relative to `e_nom` for the optimisation."""

    e_initial: float
    """Energy before the snapshots in the optimisation."""

    e_initial_per_period: bool
    """Switch: if True, then at the beginning of each investment period `e` is set to `e_initial`."""

    e_cyclic: bool
    """Switch: if True, then `e_initial` is ignored and the initial energy is set to the final energy for the group of snapshots in the optimisation."""

    e_cyclic_per_period: bool
    """Switch: if True, then the cyclic constraints are applied to each investment period separately."""

    p_set: float | None = None
    """Active power set point (for power flow only)."""

    q_set: float
    """Reactive power set point (for power flow only)."""

    e_set: float | None = None
    """Fixed energy filling level set point (for optimisation only)."""

    sign: float
    """Sign denoting orientation of the energy variable (`e`)."""

    marginal_cost: float
    """Marginal cost applied to both charging and discharging of 1 MWh."""

    marginal_cost_quadratic: float
    """Quadratic marginal cost of applied to charging and discharging of 1 MWh."""

    marginal_cost_storage: float
    """Marginal cost of energy storage of 1 MWh for one hour."""

    capital_cost: float
    """Fixed period costs of extending `e_nom` by 1 MWh, including periodized investment costs and periodic fixed O&M costs (e.g. annuitized investment costs)."""

    standing_loss: float
    """Losses per hour to energy level."""

    active: bool
    """Whether to consider the component in optimisation or not."""

    build_year: int
    """Build year."""

    lifetime: float | None = None
    """Lifetime."""


class StoreStaticResults(BaseStaticResults):
    e_nom_opt: float
    """Optimised nominal energy capacity outputed by optimisation."""


class StoreDynamicResults(BaseDynamicResults):
    p: pandas.DataFrame
    """Power at bus (positive if net supply)."""

    q: pandas.DataFrame
    """Reactive power (positive if net supply)."""

    e: pandas.DataFrame
    """Energy level of store as calculated by the optimisation."""

    mu_upper: pandas.DataFrame
    """Shadow price of upper `e_nom` limit."""

    mu_lower: pandas.DataFrame
    """Shadow price of lower `e_nom` limit."""

    mu_energy_balance: pandas.DataFrame
    """Shadow price of storage consistency equations (i.e. water values)."""


@dataclass(repr=False)
class StoreResults(BaseResults):
    static: dict[str, StoreStaticResults]
    dynamic: StoreDynamicResults
