# Generated by `generate_components.py`.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import pandas

from ._base_component import (
    BaseComponent,
    BaseDynamicResults,
    BaseResults,
    BaseStaticResults,
)


class StorageUnit(BaseComponent):
    """Storage units enable inter-temporal energy shifting with fixed nominal-energy-to-nominal-power ratio.

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/storage_units/)
    """

    class_name: Literal["StorageUnit"] = "StorageUnit"  # type: ignore

    name: str
    """Unique name."""

    bus: str
    """Name of bus to which storage unit is attached."""

    control: str
    """P,Q,V control strategy for PF, must be "PQ", "PV" or "Slack"."""

    p_nom: float
    """Nominal power for limits on `p` in optimisation. Ignored if `p_nom_extendable=True`."""

    p_nom_mod: float
    """Nominal power of the storage unit module. Introduces integer variables if set."""

    p_nom_extendable: bool
    """Switch to allow capacity `p_nom` to be extended in optimisation."""

    p_nom_min: float
    """If `p_nom_extendable=True`, set the minimum value of `p_nom_opt`."""

    p_nom_max: float | None = None
    """If `p_nom_extendable=True`, set the maximum value of `p_nom_opt`."""

    p_nom_set: float | None = None
    """If `p_nom_extendable=True`, set the value of `p_nom_opt`."""

    p_min_pu: float
    """The minimum output for each snapshot per unit of `p_nom` for the optimisation. Negative sign implies storing mode withdrawing power from bus."""

    p_max_pu: float
    """The maximum output for each snapshot per unit of `p_nom` for the optimisation. Positive sign implies discharging mode injecting power into bus."""

    p_set: float | None = None
    """Active power set point (for power flow only)."""

    q_set: float
    """Reactive power set point (for power flow only)."""

    p_dispatch_set: float | None = None
    """Active power dispatch set point (for optimisation only)."""

    p_store_set: float | None = None
    """Active power charging set point (for optimisation only)."""

    sign: float
    """Sign denoting the orientation of the dispatch variable."""

    carrier: str | None = None
    """Prime mover energy carrier (e.g. coal, gas, wind, solar); required for global constraints on primary energy in optimisation."""

    spill_cost: float
    """Cost of spilling 1 MWh."""

    marginal_cost: float
    """Marginal cost of production (discharge) of 1 MWh."""

    marginal_cost_quadratic: float
    """Quadratic marginal cost of production (discharge) of 1 MWh."""

    marginal_cost_storage: float
    """Marginal cost of energy storage of 1 MWh for one hour."""

    capital_cost: float
    """Fixed period costs of extending `p_nom` by 1 MW, including periodized investment costs and periodic fixed O&M costs (e.g. annuitized investment costs)."""

    active: bool
    """Whether to consider the component in optimisation or not."""

    build_year: int
    """Build year."""

    lifetime: float | None = None
    """Lifetime."""

    state_of_charge_initial: float
    """State of charge before the snapshots in the optimisation."""

    state_of_charge_initial_per_period: bool
    """Switch: if True, the state of charge at the beginning of an investment period is set to `state_of_charge_initial`."""

    state_of_charge_set: float | None = None
    """State of charge set points for snapshots in the optimisation."""

    cyclic_state_of_charge: bool
    """Switch: if True, then `state_of_charge_initial` is ignored and the initial state of charge is set to the final state of charge for the group of snapshots in the optimisation (`soc[-1] = soc[len(snapshots)-1]`)."""

    cyclic_state_of_charge_per_period: bool
    """Switch: if True, the cyclic constraints are applied to each investment period separately."""

    max_hours: float
    """Maximum state of charge capacity in terms of hours at full output power capacity `p_nom`."""

    efficiency_store: float
    """Efficiency of storage on the way into the storage."""

    efficiency_dispatch: float
    """Efficiency of storage on the way out of the storage."""

    standing_loss: float
    """Losses per hour to state of charge."""

    inflow: float
    """Inflow to the state of charge (e.g. due to river inflow in hydro reservoir)."""


class StorageUnitStaticResults(BaseStaticResults):
    p_nom_opt: float
    """Optimised nominal power."""


class StorageUnitDynamicResults(BaseDynamicResults):
    p: pandas.DataFrame
    """Active power at bus (positive if net generation)."""

    p_dispatch: pandas.DataFrame
    """Active power dispatch at bus."""

    p_store: pandas.DataFrame
    """Active power charging at bus."""

    q: pandas.DataFrame
    """Reactive power (positive if net generation)."""

    state_of_charge: pandas.DataFrame
    """State of charge as calculated by the optimisation."""

    spill: pandas.DataFrame
    """Spillage for each snapshot (e.g. hydro-dam letting water flow over the spillway without generating electricity)."""

    mu_upper: pandas.DataFrame
    """Shadow price of upper p_nom limit."""

    mu_lower: pandas.DataFrame
    """Shadow price of lower p_nom limit."""

    mu_state_of_charge_set: pandas.DataFrame
    """Shadow price of fixed state of charge state_of_charge_set."""

    mu_energy_balance: pandas.DataFrame
    """Shadow price of storage consistency equations."""


@dataclass(repr=False)
class StorageUnitResults(BaseResults):
    static: dict[str, StorageUnitStaticResults]
    dynamic: StorageUnitDynamicResults
