# Generated by `generate_components.py`.

from __future__ import annotations

from dataclasses import dataclass

from ._base_component import BaseResults, BaseStaticResults


class SubNetworkStaticResults(BaseStaticResults):
    name: str
    """Unique name assigned based on order of sub-network in list of sub-networks."""

    carrier: str
    """Carrier determined from the buses in the sub-network."""

    slack_bus: str
    """Name of slack bus."""


@dataclass(repr=False)
class SubNetworkResults(BaseResults):
    static: dict[str, SubNetworkStaticResults]
