# Generated by `generate_components.py`.

from __future__ import annotations

from typsa.time_variation import Static

from ._base_component import BaseComponent, BaseStaticResults


class SubNetwork(BaseComponent[Static]):
    """Subsets of buses and passive branches (i.e. lines and transformers) that are connected (i.e. synchronous areas).

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/sub-networks/)
    """


class SubNetworkOptimizationStaticResults(BaseStaticResults):
    name: str
    """Unique name assigned based on order of sub-network in list of sub-networks."""

    carrier: str
    """Carrier determined from the buses in the sub-network."""

    slack_bus: str
    """Name of slack bus."""
