# Generated by `generate_components.py`.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import pandas

from ._base_component import (
    BaseComponent,
    BaseDynamicResults,
    BaseResults,
    BaseStaticResults,
)


class Transformer(BaseComponent):
    """2-winding transformer.

    [PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/transformers/)
    """

    class_name: Literal["Transformer"] = "Transformer"  # type: ignore

    name: str
    """Unique name."""

    bus0: str
    """Name of origin bus (typically higher voltage) to which transformer is attached."""

    bus1: str
    """Name of destination bus (typically lower voltage) to which transformer is attached."""

    type: str | None = None
    """Name of 2-winding transformer standard type. If this is not an empty string "", the transformer type impedance parameters are taken from the standard type along with `num_parallel`. This will override any values set in `r`, `x`, `g`, `b`, `s_nom`, `tap_ratio`, `tap_side` and `phase_shift`. If the string is empty, values manually provided for `r`, `x`, etc. are taken."""

    model: str
    """Model used for admittance matrix; can be "t" or "pi"; defaults to "t" following physics and DIgSILENT PowerFactory."""

    x: float
    """Series reactance (per unit, using `s_nom` as base power); must be non-zero for AC branch in linear power flow. Series impedance $z = r + jx$ must be non-zero for the non-linear power flow. Ignored if type defined."""

    r: float
    """Series resistance (per unit, using `s_nom` as base power); must be non-zero for DC branch in linear power flow. Series impedance $z = r + jx$ must be non-zero for the non-linear power flow. Ignored if type defined."""

    g: float
    """Shunt conductivity (per unit, using `s_nom` as base power). Ignored if type defined."""

    b: float
    """Shunt susceptance (per unit, using `s_nom` as base power). Ignored if type defined."""

    s_nom: float
    """Limit of apparent power which can pass through branch in either direction. Ignored if `s_nom_extendable=True`."""

    s_nom_mod: float
    """Modular unit size of transformer expansion of `s_nom`. Introduces integer variables."""

    s_nom_extendable: bool
    """Switch to allow capacity `s_nom` to be extended in optimisation."""

    s_nom_min: float
    """If `s_nom_extendable=True`, set the minimum value of `s_nom_opt`."""

    s_nom_max: float | None = None
    """If `s_nom_extendable=True`, set the maximum value of `s_nom_opt`."""

    s_nom_set: float | None = None
    """If `s_nom` is extendable in optimization, set the value of `s_nom_opt`."""

    s_max_pu: float
    """The maximum allowed absolute flow per unit of `s_nom` for the oprimisation."""

    capital_cost: float
    """Fixed period costs of extending p_nom by 1 MVA, including periodized investment costs and periodic fixed O&M costs (e.g. annuitized investment costs)."""

    num_parallel: float
    """When `type` is set, this is the number of parallel transformers (can also be fractional). If `type` is empty "" this value is ignored."""

    tap_ratio: float
    """Ratio of per unit voltages at each bus for tap changed. Ignored if type defined."""

    tap_side: int
    """Defines if tap changer is modelled at the primary 0 side (usually high-voltage) or the secondary 1 side (usually low voltage) (must be 0 or 1, defaults to 0). Ignored if type defined."""

    tap_position: int
    """If the transformer has a `type`, determines position relative to the neutral tap position."""

    phase_shift: float
    """Voltage phase angle shift. Ignored if type defined."""

    active: bool
    """Whether to consider the component in optimisation or not."""

    build_year: int
    """Build year of transformer."""

    lifetime: float | None = None
    """Lifetime of transformer."""


class TransformerStaticResults(BaseStaticResults):
    sub_network: str
    """Name of connected sub-network to which transformer belongs, as calculated by `n.determine_network_topology()`. Do not set by hand."""

    x_pu: float
    """Per unit series reactance calculated by `n.calculate_dependent_values()` from `x` and `n.buses.v_nom`."""

    r_pu: float
    """Per unit series resistance calculated by `n.calculate_dependent_values()` from `r` and `n.buses.v_nom`."""

    g_pu: float
    """Per unit shunt conductivity calculated by `n.calculate_dependent_values()` from `g` and `n.buses.v_nom`."""

    b_pu: float
    """Per unit shunt susceptance calculated by `n.calculate_dependent_values()` from `b` and `n.buses.v_nom`."""

    x_pu_eff: float
    """Effective per unit series reactance for linear power flow, calculated by `n.calculate_dependent_values()` from `x`, `tap_ratio` for transformers and `n.buses.v_nom`."""

    r_pu_eff: float
    """Effective per unit series resistance for linear power flow, calculated by `n.calculate_dependent_values()` from `x`, `tap_ratio` for transformers and `n.buses.v_nom`."""

    s_nom_opt: float
    """Optimised nominal capacity for apparent power."""


class TransformerDynamicResults(BaseDynamicResults):
    p0: pandas.DataFrame
    """Active power at `bus0` (positive if branch is withdrawing power from `bus0`)."""

    q0: pandas.DataFrame
    """Reactive power at `bus0` (positive if branch is withdrawing power from `bus0`)."""

    p1: pandas.DataFrame
    """Active power at `bus1` (positive if branch is withdrawing power from `bus1`)."""

    q1: pandas.DataFrame
    """Reactive power at `bus1` (positive if branch is withdrawing power from `bus1`)."""

    mu_lower: pandas.DataFrame
    """Shadow price of lower `s_nom` limit. Always non-negative."""

    mu_upper: pandas.DataFrame
    """Shadow price of upper `s_nom` limit. Always non-negative."""


@dataclass(repr=False)
class TransformerResults(BaseResults):
    static: dict[str, TransformerStaticResults]
    dynamic: TransformerDynamicResults
