from __future__ import annotations

import csv
import subprocess
from collections.abc import Mapping
from enum import Enum
from pathlib import Path
from typing import Annotated, Any, Literal, assert_never

import pydantic
import pypsa
from datamodel_code_generator import generate
from datamodel_code_generator.enums import DataModelType, InputFileType
from pydantic.alias_generators import to_pascal, to_snake

from typsa.components._component_names import PLURAL_TO_SINGULAR_COMPONENT_NAMES

ends_with_period = pydantic.AfterValidator(
    lambda s: s.removesuffix(".") + "." if isinstance(s, str) else s
)


class _ComponentRow(pydantic.BaseModel):
    component: str
    description: Annotated[str, ends_with_period]


_ComponentAttrType = Literal[
    "boolean",
    "float",
    "int",
    "integer",
    "series",
    "static or series",
    "string",
    "list or pandas.Index",
]


class _AttrStatus(Enum):
    REQUIRED_INPUT = "Input (required)"
    OPTIONAL_INPUT = "Input (optional)"
    OUTPUT = "Output"


class _ComponentAttrRow(pydantic.BaseModel):
    attribute: str
    type: _ComponentAttrType
    unit: str
    default: str
    description: Annotated[str, ends_with_period]
    status: Annotated[_AttrStatus, pydantic.BeforeValidator(str.strip)]


_JsonSchemaType = Literal[
    "array",
    "boolean",
    "integer",
    "number",
    "string",
]


class _FieldJsonSchema(pydantic.BaseModel):
    type: _JsonSchemaType
    description: str | None = None


class _DefaultFieldJsonSchema(_FieldJsonSchema):
    default: Any


class _ConstFieldJsonSchema(_DefaultFieldJsonSchema):
    const: Any


class _JsonSchema(pydantic.BaseModel):
    title: str
    type: Literal["object"] = "object"
    description: str | None = None
    properties: Mapping[
        str,
        _FieldJsonSchema
        | _DefaultFieldJsonSchema
        | _ConstFieldJsonSchema
        | _JsonSchema,
    ]
    required: list[str]


def _component_attr_to_field_json_schema(attr: _ComponentAttrRow) -> _FieldJsonSchema:
    if attr.type == "boolean":
        json_schema_type = "boolean"
    elif attr.type == "float" or attr.type == "static or series":
        json_schema_type = "number"
    elif attr.type == "int" or attr.type == "integer":
        json_schema_type = "integer"
    elif attr.type == "list or pandas.Index" or attr.type == "series":
        json_schema_type = "array"
    elif attr.type == "string":
        json_schema_type = "string"
    else:
        assert_never(attr.type)

    if attr.status is _AttrStatus.REQUIRED_INPUT and attr.default.lower() in [
        "n/a",
        "nan",
    ]:
        return _FieldJsonSchema(type=json_schema_type, description=attr.description)

    if attr.type == "boolean":
        default = {"true": True, "false": False}[attr.default.lower()]
    elif attr.type == "float" or attr.type == "static or series":
        if attr.default.lower() in ["n/a", "nan", "inf", "-inf"]:
            return _FieldJsonSchema(type=json_schema_type, description=attr.description)
            # PyPSA will convert back to `math.nan`, `math.inf`, or `-math.inf`.
        else:
            default = float(attr.default)
    elif attr.type == "int" or attr.type == "integer":
        default = int(attr.default)
    elif attr.type == "list or pandas.Index" or attr.type == "series":
        return _FieldJsonSchema(type=json_schema_type, description=attr.description)
    elif attr.type == "string":
        if attr.default.lower() in ["n/a", "nan"]:
            return _FieldJsonSchema(type=json_schema_type, description=attr.description)
        else:
            default = attr.default
    else:
        assert_never(attr.type)

    return _DefaultFieldJsonSchema(
        type=json_schema_type, description=attr.description, default=default
    )


def _make_json_schema(
    title: str,
    required_properties: dict[str, _FieldJsonSchema | _JsonSchema],
    description: str | None = None,
) -> _JsonSchema:
    return _JsonSchema(
        title=title,
        description=description,
        properties=required_properties,
        required=list(required_properties.keys()),
    )


def _run_subprocess(args: list[str]) -> None:
    try:
        subprocess.run(args, check=True, capture_output=True)
    except subprocess.CalledProcessError as e:
        print(e.stderr)
        raise e


def _json_schema_to_py_file(
    json_schema: _JsonSchema, file_out: Path, additional_imports: list[str]
) -> None:
    file_out.parent.mkdir(parents=True, exist_ok=True)
    generate(
        additional_imports=additional_imports,
        custom_file_header="# Generated by `generate_components.py`.",
        field_constraints=True,
        formatters=[],
        input_=json_schema.model_dump(),
        input_file_type=InputFileType.JsonSchema,
        output_model_type=DataModelType.PydanticV2BaseModel,
        output=file_out,
        strict_nullable=True,
        use_default_kwarg=True,
        use_double_quotes=True,
        use_field_description=True,
        use_schema_description=True,
        use_standard_collections=True,
    )
    text = file_out.read_text()
    text = text.replace("class Private", "class _")
    file_out.write_text(text)


def _json_schemas_to_py_file(
    json_schemas: list[_JsonSchema], file_out: Path, additional_imports: list[str]
) -> None:
    all_json_schema = _make_json_schema(
        title="dummy", required_properties={x.title: x for x in json_schemas}
    )
    _json_schema_to_py_file(all_json_schema, file_out, additional_imports)
    text = file_out.read_text()
    text = text[: text.index("class Dummy") - 2]
    file_out.write_text(text)


def _process_component(
    name: str, description: str, attrs: list[_ComponentAttrRow]
) -> None:
    component_attrs_by_name = {a.attribute: a for a in attrs}
    fields: dict[str, _FieldJsonSchema] = {}
    fields["class_name"] = _ConstFieldJsonSchema(
        type="string", const=to_pascal(name), default=to_pascal(name)
    )
    fields.update(
        {
            attr.attribute: _component_attr_to_field_json_schema(attr)
            for attr in attrs
            if attr.status is not _AttrStatus.OUTPUT
            if "placeholder" not in attr.description.lower()
        }
    )
    component_json_schema = _JsonSchema(
        title=name,
        description=description,
        properties=fields,
        required=[
            n
            for n, f in fields.items()
            if (
                isinstance(f, _DefaultFieldJsonSchema)
                or component_attrs_by_name[n].status is not _AttrStatus.OPTIONAL_INPUT
            )
        ],
    )
    output_json_schemas = {
        a.attribute: _component_attr_to_field_json_schema(a)
        for a in attrs
        if a.status is _AttrStatus.OUTPUT
    }
    static_results_json_schema = _make_json_schema(
        title=f"{name}_static_results",
        required_properties={
            k: v for k, v in output_json_schemas.items() if v.type != "array"
        },
    )
    dynamic_results_json_schema = _make_json_schema(
        title=f"{name}_dynamic_results",
        required_properties={
            k: v for k, v in output_json_schemas.items() if v.type == "array"
        },
    )
    all_json_schemas = [
        component_json_schema,
        static_results_json_schema,
        dynamic_results_json_schema,
    ]
    py_file_out = Path("src", "typsa", "components", f"{name}.py")
    additional_imports = [
        "dataclasses.dataclass",
        "typing.ClassVar",
        "pandas",
        "._base_component.BaseComponent",
        "._base_component.BaseStaticResults",
        "._base_component.BaseDynamicResults",
    ]
    _json_schemas_to_py_file(all_json_schemas, py_file_out, additional_imports)

    component_class_name = to_pascal(name)
    static_results_class_name = f"{component_class_name}StaticResults"
    dynamic_results_class_name = f"{component_class_name}DynamicResults"

    text = py_file_out.read_text()
    text = text.replace(
        f"class {component_class_name}(BaseModel)",
        f"class {component_class_name}(BaseComponent)",
    )
    text = text.replace(
        f"class {static_results_class_name}(BaseModel)",
        f"class {static_results_class_name}(BaseStaticResults)",
    )
    text = text.replace(
        f"class {dynamic_results_class_name}(BaseModel)",
        f"class {dynamic_results_class_name}(BaseDynamicResults)",
    )
    try:
        idx = text.index(f"class {dynamic_results_class_name}")
    except ValueError:
        pass
    else:
        text = text[:idx] + text[idx:].replace("list[Any]", "pandas.DataFrame")
    text = text.replace('.\n    """\n    ', '."""\n\n    ')
    text = text.replace('.\n    """\n', '."""\n')
    text = text.replace('\n    """\n    ', '\n    """')
    text = text.replace('"""class_name', '"""\n\n    class_name')
    text = text.replace(
        f"class_name: Literal['{component_class_name}']",
        f'class_name: ClassVar = "{component_class_name}"\n',
    )
    py_file_out.write_text(text)

    # Lint the file (organize imports, remove any unused imports, etc.):
    _run_subprocess(args=["ruff", "check", "--fix", str(py_file_out)])
    _run_subprocess(args=["ruff", "check", "--select=I", "--fix", str(py_file_out)])

    members = [to_pascal(name)]
    if len(static_results_json_schema.properties) > 0:
        members.append(static_results_class_name)
    if len(dynamic_results_json_schema.properties) > 0:
        members.append(dynamic_results_class_name)
    Path("docs", "reference", "components", f"{name}.md").write_text(
        f"""::: components.{name}
    options:
      inherited_members: false
      members_order: source
      show_labels: false
      show_root_toc_entry: false
      show_signature_annotations: true
      show_source: false
      members: {members}
"""
    )


def main() -> None:
    root = pypsa.__file__.removesuffix("__init__.py")

    components_csv_path = Path(root, "data", "components.csv")
    components_csv_reader = csv.DictReader(components_csv_path.open())
    component_rows = [
        _ComponentRow.model_validate(row) for row in components_csv_reader
    ]
    component_descriptions = {
        to_snake(row.component): row.description for row in component_rows
    }

    component_attrs_csvs_folder = Path(root, "data", "component_attrs")
    exclude_components = [
        "line_types",
        "networks",
        "shapes",  # Contains ambiguous "geometry" type.
        "transformer_types",
    ]
    csv_paths = [
        file
        for file in component_attrs_csvs_folder.iterdir()
        if str(file).lower().endswith(".csv") and file.stem not in exclude_components
    ]
    for csv_path in csv_paths:
        print(f"Processing {csv_path}...")
        attrs_csv_reader = csv.DictReader(csv_path.open())
        attrs = [_ComponentAttrRow.model_validate(row) for row in attrs_csv_reader]
        for i, component_attr in enumerate(attrs):
            component_attr.description = component_attr.description.replace(
                "\\\\", "\\"
            )
            attrs[i] = component_attr
        name = PLURAL_TO_SINGULAR_COMPONENT_NAMES[csv_path.stem]
        description = component_descriptions[name]
        description += f"\n\n[PyPSA user guide for this component.](https://docs.pypsa.org/latest/user-guide/components/{csv_path.stem}/)"
        _process_component(name, description, attrs)


if __name__ == "__main__":
    main()
